CHANGELOG.rst, README.rst, setup.py
To run plugin code:
install plugin and pytest, goto repo that you would like to test and run: 
pytest -c <() --repo-health-check True --repo-path `pwd` --noconftest -s
Currently, output is in the form of print, but as we decided on output form, we can easily print out either a json file or csv if we want. Json file would be easier.
=> Adding repo health state script code

pytest_repo_health/plugin.py
This would check to see if current part is in a some subdirectory called "repo_health*". And since we already changed test prefix to "check", the plugin should collect the right checks.
=> Fixing test collection in pytest

pytest_repo_health/plugin.py
The new argument allows you to select if you want plugin to collect pytest_repo_health metadata and output it as a yaml file
=> Added new argument

CHANGELOG.rst, pytest_repo_health/__init__.py, pytest_repo_health/fixtures/__init__.py, pytest_repo_health/fixtures/git.py, pytest_repo_health/fixtures/github.py, pytest_repo_health/plugin.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt, setup.py, tests/__init__.py, tests/conftest.py, tests/test_fixtures.py, tests/test_repo_health.py, tox.ini
Added fixtures to fetch data from both the local git repository and the GitHub API:
* Added a `git_repo` fixture to get information about the checked out repository
* Added a `git_origin_url` fixture to get the configured SSH or HTTPS URL for the repository's origin
* Added a `github_client` fixture to initialize a GitHub API client using a personal access token from the `GITHUB_TOKEN` environment variable
* Added a `github_repo` fixture to return a github.py `Repository` object for the repo being examined.  This fixture has function scope rather than session like the other new ones, since the `loop` fixture needed to support github.py's async network calls is also function-scoped.
* Added the packages needed to work with git and the GitHub API
* Refactored the test suite to correctly run …
=> Add git and GitHub fixtures ARCHBOM-1310

CHANGELOG.rst, pytest_repo_health/__init__.py, pytest_repo_health/fixtures/github.py
We're hitting GitHub internal errors trying to fetch data from the edx-blog repository.  I've submitted a ticket to GitHub, but we should handle such cases gracefully without causing the entire health check to fail.
=> Gracefully handle errors fetching GitHub data ARCHBOM-1310

pytest_repo_health/__init__.py
Reverts edx/pytest-repo-health#27
Reverting this cause it breaks all checks that use health_metadata decorator. This change added the arguments in decorator as an argument to function, which broke every function that was not expecting an input.
Error output: 
>def wrapper(*args, **kwargs):
>        """
>       Pass output_keys as keyword argument to the function
>        """
>        kwargs['output_keys'] = output_keys
> >       func(*args, **kwargs)
>E       TypeError: check_requires() got an unexpected keyword argument 'output_keys'
>
>pytest_repo_health/__init__.py:45: TypeError`
=> Revert "[BD-18] Modified health_metadata decorator to pass output_keys to target function"

pytest_repo_health/plugin.py, tests/__init__.py, tests/conftest.py, tests/test_decorators.py, tox.ini
Adds tests to make sure the decorators don't regress and changes how the plugin "pytester" is added to work with https://docs.pytest.org/en/stable/deprecations.html#pytest-plugins-in-non-top-level-conftest-files. This deprecation was making testing locally harder.
=> Adding tests for decorators

.travis.yml, CHANGELOG.rst, setup.py, tox.ini
Removing 3.5 support since we aren't using it, it reaches EOL in about 45 days, and it's causing some confusion between different 3.5.x versions on various systems (aiohttp has dropped support for < 3.5.3).  Also added the standard `setup.py` code to simplify tagging new releases.
Not releasing a new version yet, since these changes don't add anything we need yet; just preparing this for the next release that actually includes new features.
=> Drop Python 3.5 support

CHANGELOG.rst, pytest_repo_health/__init__.py, pytest_repo_health/fixtures/github.py, requirements/base.in, requirements/base.txt, requirements/dev.txt, requirements/doc.txt, requirements/github.in, requirements/quality.txt, requirements/test.txt
Upgrade github.py to fix a bug with code of conduct parsing, and fix the git origin URL regex to handle repos with names like `.github` and `github.py`.  Make a new release, which is a major version bump due to the previously-committed drop of Python 3.5 support.
=> Upgrade github.py and fix .github repo handling ARCHBOM-1383

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
- Pinned `importlib-metadata==1.7.0` as `version>1.7.0` is causing conflicts for python36 in running `make upgrade`.
=> Pin importlib-meteadata to 1.7.0 for python36

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
- `importlib-metadata<2.0.0` was causing conflicts in running `make upgrade` with `python3.5`.
- Unpinned `importlib-metadata` constraint after fixing the issue in https://github.com/pypa/virtualenv/pull/1953 and https://github.com/tox-dev/tox/pull/1682.
=> Unpinned importlib-metadata constraint

CHANGELOG.rst, README.rst, pytest_repo_health/__init__.py, pytest_repo_health/plugin.py, tests/__init__.py, tests/test_repo_health.py
Previously, there was no way to change the file to which metadata was written. This PR adds this ability.
=> ARCHBOM-1475: Added ability to name metadata output file

requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt, requirements/travis.txt
`importlib-metadata>3.0` dropped support for `python3.5` but `Tox` and `virtualenv` require `importlib-metadata<3.0` to support `python3.5` so pinning until both packages drop support for `python3.5` & update their required `importlib-metadata` version constraint.
=> Pinned importlib-metadata<3.0 because of Tox and Virtualenv

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
`aiohttp==3.7.3(latest release)` requires [`chardet<4.0`](https://github.com/aio-libs/aiohttp/blob/2f655a59d0daedfa2a794996c4355b576c98ecc8/setup.py#L69) which is causing conflicts in make upgrade. Pinning the version in constraints until `aiohttp==4.0.0(pre-release available right now)` is released.
=> Pinned chardet<4.0 version

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt
[Python Requirements Upgrade](https://build.testeng.edx.org/job/pytest-repo-health-upgrade-python-requirements/32/display/redirect?page=changes) build failed because of the version conflict of `idna==3.1` which is pinned in `requests` as `idna<3` hence pinning the `idna` version until `requests` package removes the constraints.
=> Pin idna<3 due to requests package

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip.txt, requirements/quality.txt, requirements/test.txt
**JIRA Issue:** [BOM-2301](https://openedx.atlassian.net/browse/BOM-2301)
- Pinned `diff-cover<4.2.0` to resolve `chardet` version conflicts in the [failing requirements upgrade process](https://build.testeng.edx.org/job/pytest-repo-health-upgrade-python-requirements/35/console).
=> Pin diff-cover version

pytest_repo_health/__init__.py
For the use case where the decorator is used to add metadata for a key which only goes one level down
in results_dict.
This is for ease of use. This way, the decorator just needs to look like:
@add_key_to_metadata("key") rather than @add_key_to_metadata(("key"))
=> fix: handling the case where output is str instead of tuple

.github/workflows/upgrade-python-requirements.yml
Add new Github Action to run Requirements upgrade job against master/target branch.
After Jenkins worker has been upgraded to `Python 38`, the [Jenkins requirement upgrade build](https://build.testeng.edx.org/job/pytest-repo-health-upgrade-python-requirements/46/console) started failing because of the `Python interpreter` error.
=> build: Add requirements upgrade action

pytest_repo_health/plugin.py, pytest_repo_health/utils.py, tests/test_utils.py
When repo-health script is ran on edx-repo-health on jenkins, it gives error for import mismatch as it collects same check from both directories.
Hence if origin is same for repo_path and repo_health_path then don't import checks from repo_path
BOM-2098
=> fix: Conditional import of checks from repo-path

pytest_repo_health/plugin.py, pytest_repo_health/utils.py, tests/test_utils.py
The regex was disallowing repos with dots in their name. This commit adds
`.` as an allowable character, but includes some other changes as well:
- Remove commas from regex (not valid syntax)
- Replace `{0,1}` with `?` and remove some unneeded groupings
- Remove owner capture, since it wasn't being used
- Allow hostname and path prefix to just be matched by an undifferentiated
`.*` since we don't really care about the structure there.
- Both anchor the regex and switch to fullmatch, which is redundant but
both are best-practice unless the situation calls for something more
relaxed.
- Rename regex var to better represent its purpose.
Arguably we don't really need the git/https scheme matching, but there's a
small risk that this could be pointed at a repo cloned from a directory,
and that …
=> fix: Allow matching remote URL for .github repo (fix regex)

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/pip-tools.txt, requirements/quality.txt, requirements/test.txt
`importlib-metadata<3.0` constraint was added because of the conflict between `tox` and `virtualenv` requirements for `Python 3.5` support in https://github.com/openedx/pytest-repo-health/pull/63.
Removed the constraint now to update dependencies to latest version with `Python 3.7` and resolve the `make upgrade` job failure.
=> Remove importlib-metadata constraint

requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/doc.txt, requirements/quality.txt, requirements/test.txt
- `requests` has a pin `charset-normalizer~=2.0.0` in it so we can't bump the version unless `requests` package resolves the pin.
=> fix: pin charset-normalizer~=2.0.0

README.rst, setup.py
Because the content type is declared incorrectly as markdown, the package on PyPI looks like this:
This fixes that, and also correct one infelicity in the README formatting.
=> fix(docs): format the readme properly on PyPI, and a minimal formatting fix

requirements/ci.in, requirements/ci.txt, requirements/dev.txt, requirements/pip.txt
https://community.codecov.com/t/codecov-yanked-from-pypi-all-versions/4259
It looks like the migration was never done/finished here. I'm not sure if
we're going to continue using codecov, so I'm not going to add the GHA.
(It would need additional setup, such as provisioning with a token.)
=> fix: Remove yanked codecov package to unbreak dev

pytest_repo_health/plugin.py
From https://pytest.org/en/7.4.x/changelog.html#pytest-7-4-0-2023-06-23
> #11081: The norecursedirs check is now performed in a pytest_ignore_collect implementation, so plugins can affect it.
>
> If after updating to this version you see that your norecursedirs setting is not being respected, it means that a conftest or a plugin you use has a bad pytest_ignore_collect implementation. Most likely, your hook returns False for paths it does not want to ignore, which ends the processing and doesn’t allow other plugins, including pytest itself, to ignore the path. The fix is to return None instead of False for paths your hook doesn’t want to ignore.
=> test(fix): pytest_ignore_collect needs to return None for no opinion

README.rst, setup.py
Previously both said Apache, but this repository is AGPL3.
=> docs: Fix the license stated in README and classifiers

.github/workflows/upgrade-python-requirements.yml, catalog-info.yaml
- As per the discussion in Maintenance working group, `arbi-bom` team will maintain this repo from now on.
=> docs: add arbi-bom team as maintainer

pytest_repo_health/fixtures/github.py
1. Repo health CI workflows failing with fixture `'loop' not found` error.
2. pytest-asyncio 0.24.0+ deprecated `loop` fixture in favor of `event_loop`
**Reference:**
- Updated `fixtures/github.py` to use `event_loop` instead of deprecated `loop` fixture.
- Ensures compatibility with `pytest-asyncio >= 0.24.0`
**Note:** Re-ran the workflow with current changes and passed successfully.
[Repo Health Workflow Call](https://github.com/edx/repo-health-data/actions/runs/17265835052)
[BOMS-208](https://2u-internal.atlassian.net/browse/BOMS-208)
=> fix: changed loop to event_loop to sync with latest version of pytest.
